### PR TITLE
(maint) rename methods to match upstream

### PR DESCRIPTION
**Pull request by KevinCorcoran**
Rename methods whose names start with "set_" or "with_" to match
the names of these methods in the upstream Java project.

@jpinsonault and I discussed this the other day.

### CODE REVIEW

**Comment by fpringvaldsen** [comment]
:+1:

**Comment by cprice404** [comment]
I have mixed feelings about this.  On the one hand it'd be nice to be more consistent with the upstream.  On the other hand, the reason I changed these in the first place is because `set_` implies a mutation, and all of these methods return effectively immutable / cloned objects... and I thought that that distinction was important.

That said, if all of the rest of you guys think we should use `set` instead of `with`, it's not that big of a deal to me.

**Comment by KevinCorcoran** [comment]
Yup, I have struggled with that exact debate myself.  Talked about it with both @jpinsonault and @fpringvaldsen as well, I think all 3 of us agree that consistency with upstream is more valuable than anything else.

**Comment by KevinCorcoran** [comment]
@cprice404 just gave me a IRL :+1: on this.

**Pull request merged**
